import Image from "next/image";
import Link from "next/link";
import type { Metadata } from "next";
import type { ReactNode, SVGProps } from "react";

export const metadata: Metadata = {
  title: "About Us | AI-Powered Web App Builder",
  description:
    "Discover our mission, values, and the team behind Capacity — building AI-driven experiences to ship production-grade web apps in minutes.",
  keywords: [
    "About Capacity",
    "AI web app builder",
    "Next.js",
    "TypeScript",
    "No-code",
    "Team",
    "Mission",
  ],
  openGraph: {
    title: "About Us | AI-Powered Web App Builder",
    description:
      "We combine AI, design, and engineering to help teams build high-quality apps fast.",
    type: "website",
    url: "/about",
    images: [{ url: "/hero.webp" }],
  },
};

type Stat = {
  label: string;
  value: string;
  sub?: string;
};

type Value = {
  title: string;
  description: string;
  icon: ReactNode;
};

type TimelineItem = {
  year: string;
  title: string;
  description: string;
};

type TeamMember = {
  name: string;
  role: string;
  image: string;
  linkedin?: string;
  twitter?: string;
};

function IconSparkle(props: SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" {...props}>
      <path
        strokeWidth="1.8"
        strokeLinecap="round"
        strokeLinejoin="round"
        d="M12 3l1.8 3.9L18 8.7l-4.2 1.8L12 14.7l-1.8-4.2L6 8.7l4.2-1.8L12 3zM5 16l.9 1.9L8 19l-2.1.9L5 22l-.9-2.1L2 19l2.1-.9L5 16zM19 14l.9 1.9L22 17l-2.1.9L19 20l-.9-2.1L16 17l2.1-.9L19 14z"
      />
    </svg>
  );
}

function IconShield(props: SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" {...props}>
      <path
        strokeWidth="1.8"
        strokeLinecap="round"
        strokeLinejoin="round"
        d="M12 3l7 3v6c0 5-3.5 8-7 9-3.5-1-7-4-7-9V6l7-3z"
      />
      <path d="M9 12l2 2 4-4" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" />
    </svg>
  );
}

function IconLightning(props: SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" {...props}>
      <path d="M13 2L3 14h7l-1 8 10-12h-7l1-8z" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" />
    </svg>
  );
}

function IconUsers(props: SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" {...props}>
      <path d="M16 11c1.657 0 3-1.79 3-4s-1.343-4-3-4-3 1.79-3 4 1.343 4 3 4z" strokeWidth="1.8" />
      <path d="M8 13c2.21 0 4-2.239 4-5S10.21 3 8 3 4 5.239 4 8s1.79 5 4 5z" strokeWidth="1.8" />
      <path d="M2 21v-1a6 6 0 016-6h0" strokeWidth="1.8" strokeLinecap="round" />
      <path d="M14 21v-1c0-2.761 2.239-5 5-5h0" strokeWidth="1.8" strokeLinecap="round" />
    </svg>
  );
}

function IconGlobe(props: SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" {...props}>
      <circle cx="12" cy="12" r="9" strokeWidth="1.8" />
      <path d="M3 12h18M12 3c2.5 2.6 2.5 15.4 0 18-2.5-2.6-2.5-15.4 0-18z" strokeWidth="1.8" />
    </svg>
  );
}

function IconHeart(props: SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" {...props}>
      <path d="M12 21s-6.716-4.35-9.192-8.1C.332 9.79 2.135 6 5.82 6 8.12 6 9.774 7.2 12 9.5 14.226 7.2 15.88 6 18.18 6c3.685 0 5.488 3.79 2.012 6.9C18.716 16.65 12 21 12 21z" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" />
    </svg>
  );
}

const stats: Stat[] = [
  { label: "Apps Launched", value: "400+", sub: "Shipped to production" },
  { label: "Avg Turnaround", value: "48h", sub: "From idea to MVP" },
  { label: "Customer NPS", value: "92", sub: "/100 satisfaction" },
  { label: "Automation", value: "70%", sub: "Code generated by AI" },
];

const values: Value[] = [
  {
    title: "Build with Quality",
    description: "Production-ready code, modern patterns, and a focus on developer experience.",
    icon: <IconShield className="h-6 w-6 text-blue-600" />,
  },
  {
    title: "Move with Speed",
    description: "From idea to running app in hours, not weeks, without compromising reliability.",
    icon: <IconLightning className="h-6 w-6 text-blue-600" />,
  },
  {
    title: "Delight Users",
    description: "Accessible, responsive, and beautiful by default — designed for real users.",
    icon: <IconHeart className="h-6 w-6 text-blue-600" />,
  },
  {
    title: "Think Globally",
    description: "Scalable architectures and best practices that work for teams worldwide.",
    icon: <IconGlobe className="h-6 w-6 text-blue-600" />,
  },
  {
    title: "Earn Trust",
    description: "Transparent processes, security-first thinking, and reliable delivery.",
    icon: <IconShield className="h-6 w-6 text-blue-600" />,
  },
  {
    title: "Win Together",
    description: "We partner with you to ship outcomes, not just interfaces or code.",
    icon: <IconUsers className="h-6 w-6 text-blue-600" />,
  },
];

const timeline: TimelineItem[] = [
  {
    year: "2023",
    title: "The Idea",
    description:
      "Frustrated by slow MVP cycles, we started building an AI-first pipeline to generate production-grade apps.",
  },
  {
    year: "2024",
    title: "Private Beta",
    description:
      "Early partners launched dozens of apps across landing pages, dashboards, and full-stack prototypes.",
  },
  {
    year: "2025",
    title: "Scale & Craft",
    description:
      "We refined patterns, improved accessibility, and introduced best-in-class scaffolds for teams of all sizes.",
  },
];

const team: TeamMember[] = [
  { name: "Alex Carter", role: "Founder & CEO", image: "/1.jpg", linkedin: "#", twitter: "#" },
  { name: "Samira Khan", role: "Head of Product", image: "/2.jpg", linkedin: "#" },
  { name: "Diego Lopez", role: "Lead Engineer", image: "/3.jpg", linkedin: "#", twitter: "#" },
  { name: "Grace Chen", role: "Design Lead", image: "/4.jpg", linkedin: "#" },
];

export default function AboutPage(): JSX.Element {
  return (
    <main className="min-h-screen bg-white text-gray-900">
      {/* Hero */}
      <section className="relative overflow-hidden">
        <div className="absolute inset-0 -z-10">
          <Image src="/gradient.jpg" alt="Gradient background" fill priority className="object-cover opacity-40" />
        </div>
        <div className="relative mx-auto max-w-7xl px-6 pt-24 pb-20 sm:pt-28">
          <div className="max-w-3xl">
            <span className="inline-flex items-center gap-2 rounded-full bg-white/70 px-3 py-1 text-xs font-medium text-gray-700 shadow-sm ring-1 ring-gray-200 backdrop-blur">
              <IconSparkle className="h-4 w-4" /> Our Story
            </span>
            <h1 className="mt-4 text-4xl font-bold tracking-tight sm:text-5xl">
              We build AI workflows that ship real products
            </h1>
            <p className="mt-4 text-lg text-gray-700">
              Capacity helps teams transform napkin sketches into production-ready web applications using
              modern frameworks and AI-assisted development.
            </p>
            <div className="mt-8 flex flex-wrap items-center gap-3">
              <Link
                href="/"
                className="inline-flex items-center justify-center rounded-lg bg-blue-600 px-5 py-2.5 text-white shadow-sm transition hover:bg-blue-700 focus:outline-none focus-visible:ring-2 focus-visible:ring-blue-500/50"
              >
                Get Started
              </Link>
              <Link
                href="#team"
                className="inline-flex items-center justify-center rounded-lg border border-gray-300 bg-white px-5 py-2.5 text-gray-900 shadow-sm transition hover:bg-gray-50 focus:outline-none focus-visible:ring-2 focus-visible:ring-gray-400/40"
              >
                Meet the Team
              </Link>
            </div>
          </div>
        </div>
      </section>

      {/* Stats */}
      <section className="bg-gray-50 py-12">
        <div className="mx-auto max-w-7xl px-6">
          <div className="grid grid-cols-2 gap-6 sm:grid-cols-4">
            {stats.map((s) => (
              <div key={s.label} className="rounded-2xl bg-white p-6 text-center shadow-sm ring-1 ring-gray-100">
                <div className="text-3xl font-bold text-gray-900">{s.value}</div>
                <div className="mt-1 text-sm font-medium text-gray-600">{s.label}</div>
                {s.sub && <div className="mt-1 text-xs text-gray-500">{s.sub}</div>}
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Mission & Vision */}
      <section className="py-16">
        <div className="mx-auto max-w-7xl px-6">
          <div className="grid gap-8 lg:grid-cols-2">
            <div className="rounded-2xl border border-gray-200 bg-white p-8 shadow-sm">
              <div className="flex items-center gap-3">
                <IconLightning className="h-6 w-6 text-blue-600" />
                <h2 className="text-2xl font-semibold">Our Mission</h2>
              </div>
              <p className="mt-4 text-gray-700">
                Empower builders to ship faster with confidence. We combine AI, design systems, and best practices
                to deliver robust applications — without sacrificing quality.
              </p>
            </div>
            <div className="rounded-2xl border border-gray-200 bg-white p-8 shadow-sm">
              <div className="flex items-center gap-3">
                <IconSparkle className="h-6 w-6 text-blue-600" />
                <h2 className="text-2xl font-semibold">Our Vision</h2>
              </div>
              <p className="mt-4 text-gray-700">
                A world where anyone can turn ideas into software instantly — production-grade, accessible, and
                delightful by default.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* Values */}
      <section className="bg-gray-50 py-16">
        <div className="mx-auto max-w-7xl px-6">
          <h2 className="text-center text-3xl font-bold">Values we live by</h2>
          <div className="mt-10 grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
            {values.map((v) => (
              <div key={v.title} className="group rounded-2xl border border-gray-200 bg-white p-6 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md">
                <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-blue-50">
                  {v.icon}
                </div>
                <h3 className="mt-4 text-lg font-semibold">{v.title}</h3>
                <p className="mt-2 text-gray-600">{v.description}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Timeline */}
      <section className="py-16">
        <div className="mx-auto max-w-7xl px-6">
          <h2 className="text-3xl font-bold">Our journey</h2>
          <ol className="mt-10 space-y-8 border-l border-gray-200 pl-6">
            {timeline.map((t) => (
              <li key={t.year} className="relative">
                <span className="absolute -left-[9px] top-1.5 inline-flex h-4 w-4 items-center justify-center rounded-full bg-blue-600 ring-4 ring-white" />
                <div className="flex flex-col gap-1 sm:flex-row sm:items-center sm:gap-3">
                  <span className="inline-flex w-fit rounded-full bg-gray-100 px-2.5 py-0.5 text-xs font-medium text-gray-700 ring-1 ring-gray-200">
                    {t.year}
                  </span>
                  <h3 className="text-lg font-semibold">{t.title}</h3>
                </div>
                <p className="mt-2 max-w-3xl text-gray-700">{t.description}</p>
              </li>
            ))}
          </ol>
        </div>
      </section>

      {/* Team */}
      <section id="team" className="bg-gray-50 py-16">
        <div className="mx-auto max-w-7xl px-6">
          <div className="flex items-end justify-between gap-4">
            <div>
              <h2 className="text-3xl font-bold">Meet the team</h2>
              <p className="mt-2 text-gray-600">Small team. Big outcomes. We obsess over details so you don’t have to.</p>
            </div>
            <Link
              href="/"
              className="hidden rounded-lg border border-gray-300 bg-white px-4 py-2 text-sm font-medium text-gray-900 shadow-sm transition hover:bg-gray-50 sm:inline-flex"
            >
              Work with us
            </Link>
          </div>

          <div className="mt-10 grid gap-8 sm:grid-cols-2 lg:grid-cols-4">
            {team.map((m) => (
              <div key={m.name} className="group overflow-hidden rounded-2xl border border-gray-200 bg-white shadow-sm">
                <div className="relative h-64 w-full">
                  <Image src={m.image} alt={m.name} fill sizes="(min-width: 1024px) 25vw, (min-width: 640px) 50vw, 100vw" className="object-cover transition-transform duration-500 group-hover:scale-105" />
                </div>
                <div className="p-5">
                  <h3 className="text-lg font-semibold">{m.name}</h3>
                  <p className="text-sm text-gray-600">{m.role}</p>
                  <div className="mt-3 flex items-center gap-3">
                    {m.linkedin && (
                      <a
                        aria-label={`${m.name} on LinkedIn`}
                        href={m.linkedin}
                        className="text-gray-400 transition hover:text-gray-700"
                      >
                        <svg width="20" height="20" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true">
                          <path d="M4.98 3.5C4.98 4.88 3.86 6 2.5 6S0 4.88 0 3.5 1.12 1 2.5 1s2.48 1.12 2.48 2.5zM0 8h5v16H0V8zm7.5 0h4.8v2.2h.1c.7-1.3 2.4-2.6 4.9-2.6 5.3 0 6.3 3.5 6.3 8.1V24h-5v-7.1c0-1.7 0-3.9-2.4-3.9s-2.8 1.9-2.8 3.8V24h-5V8z" />
                        </svg>
                      </a>
                    )}
                    {m.twitter && (
                      <a
                        aria-label={`${m.name} on Twitter`}
                        href={m.twitter}
                        className="text-gray-400 transition hover:text-gray-700"
                      >
                        <svg width="20" height="20" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true">
                          <path d="M22.46 6c-.77.35-1.6.58-2.46.69a4.24 4.24 0 001.86-2.34 8.48 8.48 0 01-2.69 1.03A4.23 4.23 0 0015.5 4c-2.36 0-4.27 1.93-4.27 4.3 0 .34.04.68.11 1C7.46 9.17 4.2 7.38 2.07 4.7a4.34 4.34 0 00-.58 2.16 4.3 4.3 0 001.9 3.57 4.17 4.17 0 01-1.93-.54v.05c0 2.09 1.47 3.84 3.42 4.24-.36.1-.75.15-1.14.15-.28 0-.55-.03-.81-.08.55 1.76 2.17 3.04 4.08 3.07A8.5 8.5 0 012 19.54 11.97 11.97 0 008.29 21c7.55 0 11.68-6.34 11.68-11.84 0-.18 0-.36-.01-.53A8.48 8.48 0 0022.46 6z" />
                        </svg>
                      </a>
                    )}
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Testimonials */}
      <section className="py-16">
        <div className="mx-auto max-w-7xl px-6">
          <h2 className="text-3xl font-bold">What partners say</h2>
          <div className="mt-8 grid gap-6 md:grid-cols-2">
            <figure className="rounded-2xl border border-gray-200 bg-white p-6 shadow-sm">
              <blockquote className="text-gray-800">
                “Capacity helped us launch an MVP in days. The code quality and developer experience are top-notch.”
              </blockquote>
              <figcaption className="mt-4 text-sm text-gray-600">— Product Lead, Fintech Startup</figcaption>
            </figure>
            <figure className="rounded-2xl border border-gray-200 bg-white p-6 shadow-sm">
              <blockquote className="text-gray-800">
                “It felt like having a full-stack team on-demand. We shipped faster and validated sooner.”
              </blockquote>
              <figcaption className="mt-4 text-sm text-gray-600">— Founder, HealthTech</figcaption>
            </figure>
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="bg-blue-600 py-16 text-white">
        <div className="mx-auto max-w-7xl px-6">
          <div className="flex flex-col items-center justify-between gap-6 rounded-2xl bg-blue-700/40 p-8 ring-1 ring-white/10 md:flex-row">
            <div>
              <h3 className="text-2xl font-semibold">Ready to build something great?</h3>
              <p className="mt-2 text-blue-100">Tell us what you have in mind — we’ll help you ship it.</p>
            </div>
            <div className="flex flex-wrap gap-3">
              <Link
                href="/"
                className="inline-flex items-center justify-center rounded-lg bg-white px-5 py-2.5 font-medium text-blue-700 shadow-sm transition hover:bg-blue-50"
              >
                Start a project
              </Link>
              <a
                href="mailto:hello@example.com"
                className="inline-flex items-center justify-center rounded-lg border border-white/30 bg-transparent px-5 py-2.5 font-medium text-white shadow-sm transition hover:bg-white/10"
              >
                Contact us
              </a>
            </div>
          </div>
        </div>
      </section>
    </main>
  );
}
